server:
  port: 8085
spring:
  datasource:
    url: jdbc:oracle:thin:@172.30.3.101:1521:orcl
    username: ggfwtest
    password: ggfwtest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true